# permissions for end users to view jupyterkerneltemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jupyterkerneltemplate-viewer-role
rules:
- apiGroups:
  - kubeflow.tkestack.io
  resources:
  - jupyterkerneltemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubeflow.tkestack.io
  resources:
  - jupyterkerneltemplates/status
  verbs:
  - get
